"""Exhaustive, reviewable ownership of bounded decisions (no engine mutation).

Membership means a compiler may select a prepared action, not that the action
is safe without the normal engine checks or that its prose can be generated by
a typed model. Unrepresented work retains the actor's existing route.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DecisionDomain:
    name: str
    actions: frozenset[str]
    mode: str = "select"


def _domain(name: str, actions: str, mode: str = "select") -> DecisionDomain:
    return DecisionDomain(name, frozenset(actions.split()), mode)


DOMAINS = {item.name: item for item in (
    _domain("consumption", "buy_goods do_nothing"),
    _domain("career", "apply_job counter_job_offer accept_job_offer reject_job_offer"),
    _domain("founder_operations", "post_job hire fire make_job_offer set_price"),
    _domain("personal_finance", "apply_loan move_deposits transfer withdraw_savings buy_insurance cancel_insurance"),
    _domain("investment", "place_order cancel_orders place_ipo_bid place_fx_order cancel_fx_orders"),
    _domain("entrepreneurship", "found_company apply_business_permit attend_civic_appointment"),
    _domain("funding", "open_ipo close_ipo pitch_vc fund_pitch decline_pitch propose_term_sheet accept_term_sheet run_due_diligence close_funding_round"),
    _domain("mergers_ip", "register_ip license_ip publish_disclosure propose_merger approve_merger close_merger"),
    _domain("bank_policy", "approve_loan deny_loan set_policy_rate decide_liquidity_support"),
    _domain("contracts_legal", "propose_contract counter_contract accept_contract reject_contract perform_obligation issue_legal_notice file_claim submit_filing propose_settlement accept_settlement request_legal_counsel respond_legal_counsel end_legal_counsel"),
    _domain("judgments", "issue_legal_decision", "retain"),
    _domain("regulatory", "decide_business_permit decide_construction_permit review_merger"),
    _domain("politics", "sponsor_bill amend_bill committee_vote cast_legislative_vote cast_election_vote executive_bill_action override_veto lobby"),
    _domain("communications", "create_claim publish_information repost_information correct_claim say_public send_message reply_message forward_message", "prepared"),
    _domain("learning_compute", "buy_compute_plan cancel_compute_plan set_compute_sponsorship study_skill"),
    _domain("regional", "create_trade_shipment request_migration propose_population_movement respond_population_movement"),
    _domain("estates", "place_estate_property_bid accept_estate_property_bid withdraw_estate_property_bid place_estate_unlisted_bid accept_estate_unlisted_bid withdraw_estate_unlisted_bid"),
    _domain("construction", "construct_building cancel_urban_construction demolish_building propose_construction apply_construction_permit contribute_construction_funding perform_construction_work cancel_construction"),
    _domain("household_time", "propose_partnership propose_household_move respond_household cancel_household_proposal separate_household set_time_plan"),
    _domain("frontier", "explore_site found_settlement build_settlement move_settlement charter_region"),
)}
ACTION_DOMAIN = {action: domain.name for domain in DOMAINS.values() for action in domain.actions}
COMMONS_OPERATIONS = frozenset({"post", "react", "read", "follow", "join_community",
                              "create_community", "moderate", "appeal"})
SELECTION_SERVICES = frozenset({"commons", "attention", "newsroom", "oracle_tools", "oracle_forecast", "hermes_helper"})
TYPED_PURPOSES = frozenset({"decision", "founder", "credit_officer", "vc_partner", "central_banker",
    "lawyer", "permit_clerk", "regulator", "competition_regulator", "judge", "legislator",
    "executive", "gov_official", "public_trustee", "construction_permit_clerk",
    "legislator_house", "legislator_senate", "labor_regulator", "lobbyist", "exchange",
    "preflight", "decision_evaluation", "commons_selection", "attention_selection",
    "newsroom_selection", "oracle_tool_selection", "oracle_forecast", "election_ballot", "hermes_selection"})


def validate_coverage(action_types: set[str]) -> None:
    """Fail closed when a newly registered command has no explicit owner."""
    if len(ACTION_DOMAIN) != sum(len(domain.actions) for domain in DOMAINS.values()):
        raise ValueError("decision domains overlap")
    if set(ACTION_DOMAIN) != set(action_types):
        raise ValueError(f"decision coverage differs: missing={sorted(set(action_types) - ACTION_DOMAIN.keys())}; "
                         f"unknown={sorted(ACTION_DOMAIN.keys() - set(action_types))}")
